export interface MedicationOrder {
  id: number;
  drug: string;
  order: string;
  group: string;
  route: string;
  dilution: boolean;
  note?: string;
  dilutionDetail?: string;
}

export const medicationData: MedicationOrder[] = [
  {
    id: 1,
    drug: "CIPROFLOXACIN POLPHARMA 0,2% 200ml (Ciprofloxacin - 200mg/100ml)",
    order: "Truyền tĩnh mạch, ngày 2 lần, Sáng 200ml, tối 200ml, 30 giọt/phút",
    group: "Kháng sinh",
    route: "Truyền tĩnh mạch",
    dilution: false,
  },
  {
    id: 2,
    drug: "MEROVIA i-1000mg (Meropenem* - 1000mg)",
    order: "Truyền tĩnh mạch ngày 3 lần, sáng 1 lọ, chiều 1 lọ, tối 1 lọ, 20 giọt/phút",
    group: "Kháng sinh",
    route: "Truyền tĩnh mạch",
    dilution: true,
    note: "*Pha NaCL - Natri Clorid 0,9% 100ml. Truyền tĩnh mạch ngày 3 lần, sáng 100ml, chiều 100ml, tối 100ml, 20 giọt/phút",
  },
  {
    id: 3,
    drug: "METRONIDAZOLE Allomed inf 500mg/100ml",
    order: "Truyền tĩnh mạch ngày 3 lần, sáng 100ml, chiều 100ml, tối 100ml, 20 giọt/phút",
    group: "Kháng sinh",
    route: "Truyền tĩnh mạch",
    dilution: false,
  },
  {
    id: 4,
    drug: "VALBIVI i-1g (Vancomycin - 1000mg (hoạt lực))",
    order: "Truyền tĩnh mạch ngày 2 lần, sáng 1 lọ, tối 1 lọ",
    group: "Kháng sinh",
    route: "Truyền tĩnh mạch",
    dilution: true,
    note: "*Pha NaCL - Natri Clorid 0,9% 250ml. Truyền tĩnh mạch ngày 2 lần, sáng 250 ml, tối 250 ml, 20 giọt/phút",
  },
  {
    id: 5,
    drug: "Ciprobay 400mg inf 400mg/200ml",
    order: "Truyền tĩnh mạch, ngày 2 lần, sáng 200ml, tối 200ml, 30 giọt/phút",
    group: "Kháng sinh",
    route: "Truyền tĩnh mạch",
    dilution: false,
  },
  {
    id: 6,
    drug: "TENAMYD-CEFTAZIDIME i-2000mg (Ceftazidim - 2000mg)",
    order: "Tiêm tĩnh mạch ngày 3 lần, sáng 1 lọ, chiều 1 lọ, tối 1 lọ",
    group: "Kháng sinh",
    route: "Tiêm tĩnh mạch",
    dilution: true,
    note: "*Pha Nước cất - Nước cất pha tiêm 5ml/10ml. Tiêm tĩnh mạch ngày 3 lần, sáng 2 ống (5ml)/1 ống (10ml), chiều 2 ống (5ml)/1 ống (10ml), tối 2 ống (5ml)/1 ống (10ml)",
  },
  {
    id: 7,
    drug: "THERMODOL i-1g",
    order: "Truyền tĩnh mạch ngày 3 lần, sáng 100ml, chiều 100ml, tối 100ml, 100 giọt/phút",
    group: "Giảm đau",
    route: "Truyền tĩnh mạch",
    dilution: false,
  },
  {
    id: 8,
    drug: "SOLU-MEDROL i-40mg",
    order: "Tiêm tĩnh mạch ngày 1 lần, sáng 1 lọ",
    group: "Kháng viêm",
    route: "Tiêm tĩnh mạch",
    dilution: false,
  },
  {
    id: 9,
    drug: "NAPROZOLE-R i-20mg (Rabeprazole - 20mg)",
    order: "Tiêm tĩnh mạch, sáng 1 lọ",
    group: "Băng dạ dày",
    route: "Tiêm tĩnh mạch",
    dilution: true,
    note: "*Pha Nước cất - Nước cất pha tiêm 5ml. Tiêm tĩnh mạch, sáng 1 lọ",
  },
  {
    id: 10,
    drug: "AMIPAREN inf 10% 200ml* (dịch truyền hỗn hợp acid amin - 10%)",
    order: "Truyền tĩnh mạch, sáng 400 ml, 30 giọt/phút",
    group: "Dinh dưỡng",
    route: "Truyền tĩnh mạch",
    dilution: true,
  },
  {
    id: 11,
    drug: "GLUCOSE 5% inf 5% 500ml IVC",
    order: "Truyền tĩnh mạch, sáng 500ml, chiều 500ml",
    group: "Dinh dưỡng",
    route: "Truyền tĩnh mạch",
    dilution: true,
    note: "Pha INSULIN ACTRAPID & POTASSIUM CHLORIDE. Điều trị theo hội chẩn nội tiết",
  },
  {
    id: 12,
    drug: "VINPHASON i-100mg (Hydrocortison - 100mg)",
    order: "Tiêm tĩnh mạch, ngày 2 lần, sáng 1 ống, tối 1 ống",
    group: "Kháng viêm",
    route: "Tiêm tĩnh mạch",
    dilution: false,
  },
  {
    id: 13,
    drug: "RINGER LACTATE inf 500ml FKB (Lactat ringer - 0,135g; 0,2g; 3g; 1,6g)/500ml)",
    order: "Truyền tĩnh mạch ngày 1 lần, sáng 500ml, 20 giọt/phút",
    group: "Dinh dưỡng",
    route: "Truyền tĩnh mạch",
    dilution: false,
  },
  {
    id: 14,
    drug: "FLEXBUMIN inf 20% 50ml BH70% (Albumin - 10g/50ml)",
    order: "Truyền tĩnh mạch ngày 2 lần, sáng 50ml, tối 50ml, 20 giọt/phút",
    group: "Dinh dưỡng",
    route: "Truyền tĩnh mạch",
    dilution: false,
  },
  {
    id: 15,
    drug: "ALBUTEIN inf 25% 50ml Grifol BH70% (Albumin người - 25% x 50ml)",
    order: "Truyền tĩnh mạch, ngày 2 lần, sáng 50ml, tối 50ml, 20 giọt/phút",
    group: "Dinh dưỡng",
    route: "Truyền tĩnh mạch",
    dilution: false,
  },
  {
    id: 16,
    drug: "POTASSIUM CHLORIDE PROAMP i-10% (Potassium chloride - 1g/10ml)",
    order: "Uống qua sonde, ngày 3 lần, sáng 2 ống, chiều 2 ống, tối 2 ống",
    group: "Dinh dưỡng",
    route: "Uống",
    dilution: false,
  },
  {
    id: 17,
    drug: "MAGNE SULF i-15% 10ml Bidipha + (Magnesi sulfat - 1,5g/10ml)",
    order: "",
    group: "Dinh dưỡng",
    route: "Truyền tĩnh mạch",
    dilution: false,
  },
  {
    id: 18,
    drug: "(Ampicilline/Sulbactam - 1,5g)",
    order: "Tiêm tĩnh mạch, ngày 2 lần, sáng 1 lọ, tối 1 lọ",
    group: "Kháng sinh",
    route: "Tiêm tĩnh mạch",
    dilution: true,
    note: "*Pha nước cất - Nước cất pha tiêm 5ml. Tiêm tĩnh mạch, ngày 2 lần, sáng 2 lọ, tối 2 lọ",
  },
  {
    id: 19,
    drug: "TRASOLU i-100mg/2ml (Tramadol - 100mg/2ml)",
    order: "Tiêm bắp ngày 1 lần, tối 1 ống",
    group: "Giảm đau",
    route: "Tiêm bắp",
    dilution: false,
  },
  {
    id: 20,
    drug: "SOLUMEDROL i-500mg (Methyl prednisolone 500mg)",
    order: "Truyền tĩnh mạch, sáng 1 lọ",
    group: "Kháng viêm",
    route: "Truyền tĩnh mạch",
    dilution: true,
    note: "*Pha Glucose 5% 250ml: Truyền tĩnh mạch, sáng 250ml, 30 giọt/phút",
  },
  {
    id: 21,
    drug: "CEFAMANDOL Imexpharm i-0,5g (Cefamandol 0,5g)",
    order: "Tiêm tĩnh mạch, sáng 2 lọ, chiều 2 lọ, tối 2 lọ",
    group: "Kháng sinh",
    route: "Tiêm tĩnh mạch",
    dilution: true,
    note: "*Pha nước cất 5ml/10ml: Tiêm tĩnh mạch, sáng 2 ống(5ml)/ 1 ống(10ml), trưa 2 ống(5ml)/ 1 ống(10ml), tối 2 ống(5ml)/ 1 ống(10ml)",
  },
  {
    id: 22,
    drug: "CYCLONAMINE i-12,5% 250mg/2ml (Etamsylat - 250mg/2ml)",
    order: "Tiêm tĩnh mạch, sáng 2 ống, tối 2 ống",
    group: "Cầm máu",
    route: "Tiêm tĩnh mạch",
    dilution: false,
    note: "Thuốc hậu phẫu",
  },
  {
    id: 23,
    drug: "GLUCOLYTE-2 inf 500ml OTSUKA (Dextrose + KCl + NaCl + Monobasic kali phosphat + Natri Acetate + Nacl + Kẽm sulfat)",
    order: "Truyền tĩnh mạch, Chiều 500ml, 30 giọt/phút",
    group: "Dinh dưỡng",
    route: "Truyền tĩnh mạch",
    dilution: false,
    note: "Thuốc hậu phẫu",
  },
  {
    id: 24,
    drug: "BACSULFO i-1g/0,5g + (Cefoperazon + sulbactam - 1g + 0,5g)",
    order: "Tiêm tĩnh mạch, chiều 1 lọ",
    group: "Kháng sinh",
    route: "Tiêm tĩnh mạch",
    dilution: false,
    note: "Thuốc hậu phẫu. *Pha nước cất 5ml/10ml: Tiêm tĩnh mạch, chiều 2 ống(5ml)/ 1 ống(10ml)",
  },
  {
    id: 25,
    drug: "CYCLONAMINE i-12,5% 250mg/2ml (Etamsylat)",
    order: "Tiêm tĩnh mạch, chiều 2 ống",
    group: "Cầm máu",
    route: "Tiêm tĩnh mạch",
    dilution: false,
    note: "Thuốc hậu phẫu",
  },
  {
    id: 26,
    drug: "ROCURONIUM i-50mg/5ml Rocuronium Bromid - 50mg/5ml) x 5 (Ống)",
    order: "Truyền tĩnh mạch, chiều 5 ống, 5 ml/h",
    group: "",
    route: "Truyền tĩnh mạch",
    dilution: true,
    note: "- NATRI CLORID 0,9% 100ml. Truyền tĩnh mạch, chiều 50 ml, 5 ml/h",
  },
  {
    id: 27,
    drug: "HEPARIN-Belmed i-25000UI + (Heparin natri - 25.000UI /5ml)",
    order: "Bơm tiêm điện, sáng 5000 ui, 5 ml/h. Ghi chú: Duy trì raptt 1.5-2s",
    group: "",
    route: "",
    dilution: true,
    note: "- NATRI CLORID 0,9% 100ml. Bơm tiêm điện, sáng 50 ml",
  },
  {
    id: 28,
    drug: "VINPHYTON i-10mg + (Phytomenadion (vitamin K1) - 10mg/1ml) x 2 (Ống)",
    order: "Tiêm tĩnh mạch, chiều 1 ống, đêm 1 ống",
    group: "",
    route: "Tiêm tĩnh mạch",
    dilution: false,
  },
  {
    id: 29,
    drug: "LEVOGOLDS inf 750mg 150ml + (Levofloxacin - 750mg/150ml)",
    order: "Truyền tĩnh mạch, chiều 150 ml, 50 giọt/ph",
    group: "Kháng sinh",
    route: "Truyền tĩnh mạch",
    dilution: false,
  },
  {
    id: 30,
    drug: "Fentanyl B.Braun i-100mcg/2ml + (Fentanyl - 100mcg/2ml) x 15 (Ống)",
    order: "Truyền tĩnh mạch, chiều 5 ống, tối 5 ống, đêm 5 ống, 5 ml/h",
    group: "",
    route: "",
    dilution: true,
    note: "Truyền tĩnh mạch, chiều 50 ml, tối 50 ml, đêm 50 ml, 5 ml/h",
  },
  {
    id: 31,
    drug: "Zodalan i- 5mg/1ml + (Midazolam - 5mg/1ml) x 15 (Ống)",
    order: "",
    group: "",
    route: "",
    dilution: true,
    note: "- NATRI CLORID 0,9% 100ml x 2 (Túi)",
  },
  {
    id: 32,
    drug: "TAMIFLU v-75mg",
    order: "Uống, chiều 1 viên, đêm 1 viên. Ghi chú: mỗi 12h",
    group: "",
    route: "Uống",
    dilution: false,
  },
  {
    id: 33,
    drug: "DUPHALAC gói 10g/15ml",
    order: "Uống, chiều 1 gói, đêm 1 gói",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 34,
    drug: "NEPHROSTERIL",
    order: "",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 35,
    drug: "Tracutil",
    order: "",
    group: "Dinh dưỡng",
    route: "",
    dilution: false,
  },
  {
    id: 36,
    drug: "Cernevit",
    order: "",
    group: "Dinh dưỡng",
    route: "",
    dilution: false,
  },
  {
    id: 37,
    drug: "DIAZEPAM i-10mg 2ml Vidipha + (Diazepam - 10mg/2ml)",
    order: "Tiêm tĩnh mạch, sáng 0.5 ống, chiều 0.5 ống, tối 0.5 ống, đêm 0.5 ống",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 38,
    drug: "Takizd i-20mg/2ml",
    order: "Tiêm tĩnh mạch",
    group: "Lợi tiểu",
    route: "Tiêm tĩnh mạch",
    dilution: false,
  },
  {
    id: 39,
    drug: "COLISTIMETHATE i- 4.5 MIU (150 mg) Xellia * + (Colistin - 4.5 MIU (150 mg)) x 2 (Lọ)",
    order: "Truyền tĩnh mạch, sáng 2 lọ, 20 giọt/ph. Ghi chú: Liều bolus 1",
    group: "Kháng sinh",
    route: "Truyền tĩnh mạch",
    dilution: true,
    note: "- NATRI CLORID 0,9% 100ml. Truyền tĩnh mạch, sáng 100 ml, 20 giọt/ph",
  },
  {
    id: 40,
    drug: "BACTRIM® i- 400mg/80mg [ngoài DM] (Sulfamethoxazol + Trimethoprim - 400mg + 80mg) x 6 (Ống)",
    order: "Truyền tĩnh mạch, chiều 2 ống, tối 2 ống, đêm 2 ống, 20 giọt/ph. Ghi chú: mỗi 8h",
    group: "Kháng sinh",
    route: "Truyền tĩnh mạch",
    dilution: true,
    note: "- GLUCOSE 5% 250ml x 3 (Chai). Truyền tĩnh mạch, chiều 250 ml, tối 250 ml, đêm 250 ml",
  },
  {
    id: 41,
    drug: "CANCIDAS i-70mg * + (Caspofungin - 70mg) x 1 (Lọ)",
    order: "Truyền tĩnh mạch, sáng 1 lọ, 20 giọt/ph, liều tải",
    group: "",
    route: "Truyền tĩnh mạch",
    dilution: true,
    note: "- NATRI CLORID 0,9% 100ml",
  },
  {
    id: 42,
    drug: "VITAMIN B1 i-100mg Vinphaco + (Thiamin hydroclorid - 100mg/1ml) x 2 (Ống)",
    order: "Tiêm bắp, chiều 1 ống, đêm 1 ống",
    group: "Dinh dưỡng",
    route: "Tiêm bắp",
    dilution: false,
  },
  {
    id: 43,
    drug: "MYCAZOLE v-200mg + (Fluconazol - 200mg) x 2 (Viên)",
    order: "Uống, chiều 2 viên",
    group: "Kháng nấm",
    route: "Uống",
    dilution: false,
  },
  {
    id: 44,
    drug: "DIPRIVAN i-1% 20ml + (Propofol - 10mg/ml) x 2 (Ống)",
    order: "Truyền tĩnh mạch, sáng 2 ống, 3 ml/h",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 45,
    drug: "SMOFLIPID",
    order: "",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 47,
    drug: "NICARDIPIN Aguettant i-10mg/10ml + (NICARDIPIN - 10mg/10ml) x 6 (Lọ)",
    order: "Truyền tĩnh mạch, chiều 2 lọ, tối 2 lọ, đêm 2 lọ, 7 ml/h. Ghi chú: duy trì HATB # 75 mmHg",
    group: "",
    route: "Truyền tĩnh mạch",
    dilution: true,
    note: "- NATRI CLORID 0,9% 100ml x 2 (Túi)",
  },
  {
    id: 48,
    drug: "LINEZOLID KABI i-(2mg/ml) x 300ml * + (Linezolid - (2mg/ml) x 300ml) x 2 (Túi)",
    order: "Truyền tĩnh mạch, tối 300 ml, đêm 300 ml, 20 giọt/ph",
    group: "Kháng sinh",
    route: "Truyền tĩnh mạch",
    dilution: false,
  },
  {
    id: 49,
    drug: "Tanganil 500mg/5ml",
    order: "1 ống Tiêm tĩnh mạch",
    group: "",
    route: "Tiêm tĩnh mạch",
    dilution: false,
  },
  {
    id: 50,
    drug: "Gikanin 500mg",
    order: "1 viên uống",
    group: "",
    route: "Uống",
    dilution: false,
  },
  {
    id: 51,
    drug: "Betahistin 24mg",
    order: "1 viên uống",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 52,
    drug: "Sulpirid 100mg",
    order: "",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 53,
    drug: "Buscopan 10mg",
    order: "1 viên uống",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 54,
    drug: "No-Spa Forte 40mg",
    order: "",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 55,
    drug: "Drotusc 40mg",
    order: "",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 56,
    drug: "litopau 50mg",
    order: "",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 57,
    drug: "Trimebutine maleate 200mg",
    order: "",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 58,
    drug: "Loperamid 2mg",
    order: "",
    group: "",
    route: "",
    dilution: false,
  },
  {
    id: 59,
    drug: "Macfor 3g",
    order: "",
    group: "",
    route: "",
    dilution: false,
  },
];
